### ISSUE TITLE
profile not found (tik tok ban in our country)

### ISSUE THREAD

**Issue by RazyRo** [Jettcodey/TikTok-Downloader#11]
is it due to ban in our country or any other issue?

**Comment by Jettcodey** [comment]
Hey, could you enable the Download and Json-log files in the Settings dialog, then try downloading again. 
The logs are getting Saved in a folder Named "TTDownloader-Logs[YYYY-MM-DD_xx-xx]-Logs" on the Desktop, Just Zip the folder and upload it here so I can analyze the issue?

![image1](https://github.com/user-attachments/assets/159b48a7-04b2-4f48-960f-b32c7165a35d)
![image2](https://github.com/user-attachments/assets/6cca0177-dac6-4844-96e3-0aa7da303d7c)
![image3](https://github.com/user-attachments/assets/a9a0a73b-9ad3-40ef-8a7e-499653d3a85e)

**Comment by Jettcodey** [comment]
@RazyRo, is this still an issue you're having or not?
