### ISSUE TITLE
App downloads a random video when current url doesn't exist

### ISSUE THREAD

**Issue by parasiteoflife** [Jettcodey/TikTok-Downloader#12]
I have a bunch of IDs I want to download, I don't know whether they are video or photo items and I don't know the username either so I have built all urls using `placeholder` for the username and `/video/`.  

When one url doesn't exist instead of reporting and skiping it the app downloads a random video/photo (I think it's from the recommended/home?)

Here is one url: https://www.tiktok.com/@placeholder/video/7128671073558174010

**Comment by Jettcodey** [comment]
Hi @parasiteoflife,

Looks like I missed adding a check to stop, log, and skip the download when a URL doesn’t exist or doesn't have the intended video/photo. As you pointed out, the app currently grabs random recommended videos/photos from TikTok when the URL is invalid.

I’ll work on a fix when I get a chance, but life’s pretty busy right now, so I’m not sure when it’ll be ready.

**Comment by Jettcodey** [comment]
@parasiteoflife Issue is Fixed now, Thanks Reporting :)
