### ISSUE TITLE
[Feature Request] HD bulk download ( Mass Download ) 

### ISSUE THREAD

**Issue by ABF-GIT** [Jettcodey/TikTok-Downloader#13]
It's simple request if that even possible to download in bulk ( mass download ) as Highest Quality Video such HD

**Comment by ABF-GIT** [comment]
thanks there is example here : https://tikdownloader.io/en
if you put any tiktok link and download MP4 HD u will get high quality videos as 20 mb / 14 mb always check it maybe u can get some information

**Comment by Jettcodey** [comment]
Hey @ABF-GIT, 
I just published Pre-Release 1.3.1 with HD download functionality, which you can check out [here](https://github.com/Jettcodey/TikTok-Downloader/releases/tag/Pre-Release-1.3.1). 
 (HD downloads are a workaround for your other Issue #14.)
It would be nice if you could provide some feedback if you decide to test this pre-release!

Sadly, HD downloads do not (yet) work with the option "Mass Download by Username."

**Comment by Jettcodey** [comment]
Available now for the Full [Release 1.3.1](https://github.com/Jettcodey/TikTok-Downloader/releases/tag/Release-1.3.1)
HD Mass Download By Username Soon

**Comment by MNaymaN** [comment]
I have the 1.3.1 version and  xxxxx_combined_links.txt file 
when downloading "mass download from text file links" it work okay
but when i try "HD download from text file links"  it gives error 
Invalid URL: Not a Video URL! URL provided: C:\users\pc blablabla xxxxx_combined_links.txt

**Comment by Jettcodey** [comment]
Hey @MNaymaN I'll take a look at that issue as soon as possible.

**Comment by Jettcodey** [comment]
Hey @MNaymaN , The issue has been resolved in the latest update!

**Comment by ABF-GIT** [comment]
> Available now for the Full [Release 1.3.1](https://github.com/Jettcodey/TikTok-Downloader/releases/tag/Release-1.3.1) HD Mass Download By Username Soon

thank you brother
