### ISSUE TITLE
[Bug] Cant open in windows 11 ( auto close )

### ISSUE THREAD

**Issue by JMBT666** [Jettcodey/TikTok-Downloader#15]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 
4. 

**Expected behavior**

**Screenshots**

**Application Logs Available?**
If applicable, add the log-files to help explain your problem.

**Additional context**

**Comment by Jettcodey** [comment]
Please fill out the template and provide additional information, such as system logs, video proof, etc.
This issue is closed due to insufficient information.
