### ISSUE TITLE
[SUGGESTION]Save To /username/photos or /username/videos

### ISSUE THREAD

**Issue by snapboss** [Jettcodey/TikTok-Downloader#2]
Hey, just tried the software and tried to mass download using txt file with links.

When saving, it saves to /username/videoid_video/video.mp4 

What if you can make it so it saves only at /username/videos and photos at /username/photos/

It would be much easier to scroll through everything or even organize them. 

If this is not in your vision, make a setting/option inside app to allow users to save them in this method.
Edit: Also, if possible, I don't know if it can be done without breaking anything,but to increase the download speed, can download be in multithreads for faster downloading?

**Comment by Jettcodey** [comment]
Thanks for trying the downloader and sharing your suggestion! 

- I'll be adding an option in the app settings for editing the file structure. 

> just FYI: I made the file structure as it is currently because I noticed that Windows seems to struggle loading all the video and image previews, which increased the loading times by up to 10 seconds depending on how many videos and images are stored in one user folder. And yes, sure, turning off previews would be an option, but it doesn't make it easy finding specific videos, if you ask me.

- Regarding multithreaded (faster) downloading, I'll explore ways to implement it without compromising stability.

Thank you for your feedback, Appreciate it :)

**Comment by Jettcodey** [comment]
Hey @snapboss ,
Just wanted to inform you that I've implemented your request for the file structure change, and it's ready for the next release.

#### - Regarding multithreaded (faster) downloading, it's a bit harder than I thought at the moment, but it's something I want to add in the next couple of releases to come.

**Comment by snapboss** [comment]
> Hey @snapboss , Just wanted to inform you that I've implemented your request for the file structure change, and it's ready for the next release.
> 
> #### - Regarding multithreaded (faster) downloading, it's a bit harder than I thought at the moment, but it's something I want to add in the next couple of releases to come.

Perfect. As per faster downloading, it's fine if it's not possible right now. I can always split the links list in 2 parts and open 2 instances of the app.
