### ISSUE TITLE
[Bug] Unhandled exception

### ISSUE THREAD

**Issue by T-prog3** [Jettcodey/TikTok-Downloader#21]
Got this when trying out the HD Download feature.

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.Net.Http.HttpIOException: The response ended prematurely. (ResponseEnded)
>    at System.Net.Http.HttpConnection.FillAsync(Boolean async)
>    at System.Net.Http.HttpConnection.CopyToContentLengthAsync(Stream destination, Boolean async, UInt64 length, Int32 bufferSize, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnection.ContentLengthReadStream.CompleteCopyToAsync(Task copyTask, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
> 
> 
> ************** Loaded Assemblies **************
> System.Private.CoreLib
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Private.CoreLib.dll
> ----------------------------------------
> TikTok Downloader
>     Assembly Version: 1.3.2.0
>     Location: C:\Users\Desktop\AppData\Local\Programs\Jettcodey\TikTok Downloader\TikTok Downloader\TikTok Downloader.dll
> ----------------------------------------
> System.Runtime
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Runtime.dll
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.10\System.Windows.Forms.dll
> ----------------------------------------
> System.ComponentModel.Primitives
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.ComponentModel.Primitives.dll
> ----------------------------------------
> System.Windows.Forms.Primitives
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.10\System.Windows.Forms.Primitives.dll
> ----------------------------------------
> System.Drawing.Primitives
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Drawing.Primitives.dll
> ----------------------------------------
> System.Collections.Specialized
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Collections.Specialized.dll
> ----------------------------------------
> System.Runtime.InteropServices
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Runtime.InteropServices.dll
> ----------------------------------------
> System.Threading
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Threading.dll
> ----------------------------------------
> System.Diagnostics.TraceSource
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Diagnostics.TraceSource.dll
> ----------------------------------------
> System.Collections
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Collections.dll
> ----------------------------------------
> System.Drawing.Common
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.10\System.Drawing.Common.dll
> ----------------------------------------
> Microsoft.Win32.Primitives
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\Microsoft.Win32.Primitives.dll
> ----------------------------------------
> System.ComponentModel.EventBasedAsync
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.ComponentModel.EventBasedAsync.dll
> ----------------------------------------
> System.Threading.Thread
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Threading.Thread.dll
> ----------------------------------------
> Accessibility
>     Assembly Version: 4.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.10\Accessibility.dll
> ----------------------------------------
> System.ComponentModel.TypeConverter
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.ComponentModel.TypeConverter.dll
> ----------------------------------------
> Microsoft.Win32.SystemEvents
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.10\Microsoft.Win32.SystemEvents.dll
> ----------------------------------------
> System.Collections.Concurrent
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Collections.Concurrent.dll
> ----------------------------------------
> System.ComponentModel
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.ComponentModel.dll
> ----------------------------------------
> System.Numerics.Vectors
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Numerics.Vectors.dll
> ----------------------------------------
> System.Memory
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Memory.dll
> ----------------------------------------
> System.Runtime.Loader
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Runtime.Loader.dll
> ----------------------------------------
> System.Resources.Extensions
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.10\System.Resources.Extensions.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\8.0.10\System.Drawing.dll
> ----------------------------------------
> System.ObjectModel
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.ObjectModel.dll
> ----------------------------------------
> System.Xml.XmlSerializer
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Xml.XmlSerializer.dll
> ----------------------------------------
> System.Private.Xml
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Private.Xml.dll
> ----------------------------------------
> System.Collections.NonGeneric
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Collections.NonGeneric.dll
> ----------------------------------------
> System.Text.Encoding.Extensions
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Text.Encoding.Extensions.dll
> ----------------------------------------
> System.Reflection.Emit.ILGeneration
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Reflection.Emit.ILGeneration.dll
> ----------------------------------------
> System.Reflection.Emit
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Reflection.Emit.dll
> ----------------------------------------
> Microsoft.GeneratedCode
>     Assembly Version: 1.0.0.0
>     Location: 
> ----------------------------------------
> System.Reflection.Primitives
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Reflection.Primitives.dll
> ----------------------------------------
> System.Text.RegularExpressions
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Text.RegularExpressions.dll
> ----------------------------------------
> System.Private.Uri
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Private.Uri.dll
> ----------------------------------------
> Microsoft.Win32.Registry
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\Microsoft.Win32.Registry.dll
> ----------------------------------------
> System.Linq
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Linq.dll
> ----------------------------------------
> System.Management
>     Assembly Version: 8.0.0.0
>     Location: C:\Users\Desktop\AppData\Local\Programs\Jettcodey\TikTok Downloader\TikTok Downloader\runtimes\win\lib\net8.0\System.Management.dll
> ----------------------------------------
> System.IO.FileSystem.DriveInfo
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.IO.FileSystem.DriveInfo.dll
> ----------------------------------------
> System.Diagnostics.Process
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Diagnostics.Process.dll
> ----------------------------------------
> System.Threading.ThreadPool
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Threading.ThreadPool.dll
> ----------------------------------------
> System.Net.Http
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Net.Http.dll
> ----------------------------------------
> System.Net.Primitives
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Net.Primitives.dll
> ----------------------------------------
> Newtonsoft.Json
>     Assembly Version: 13.0.0.0
>     Location: C:\Users\Desktop\AppData\Local\Programs\Jettcodey\TikTok Downloader\TikTok Downloader\Newtonsoft.Json.dll
> ----------------------------------------
> System.Linq.Expressions
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Linq.Expressions.dll
> ----------------------------------------
> Microsoft.CSharp
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\Microsoft.CSharp.dll
> ----------------------------------------
> System.Diagnostics.Tracing
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Diagnostics.Tracing.dll
> ----------------------------------------
> System.Diagnostics.DiagnosticSource
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Diagnostics.DiagnosticSource.dll
> ----------------------------------------
> System.Net.Security
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Net.Security.dll
> ----------------------------------------
> System.Security.Cryptography
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Security.Cryptography.dll
> ----------------------------------------
> System.Net.Sockets
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Net.Sockets.dll
> ----------------------------------------
> System.Threading.Overlapped
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Threading.Overlapped.dll
> ----------------------------------------
> System.Net.NameResolution
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Net.NameResolution.dll
> ----------------------------------------
> System.Runtime.Intrinsics
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Runtime.Intrinsics.dll
> ----------------------------------------
> System.Security.Principal.Windows
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Security.Principal.Windows.dll
> ----------------------------------------
> System.Security.Claims
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Security.Claims.dll
> ----------------------------------------
> System.Runtime.Serialization.Formatters
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Runtime.Serialization.Formatters.dll
> ----------------------------------------
> System.Runtime.Serialization.Primitives
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Runtime.Serialization.Primitives.dll
> ----------------------------------------
> System.Runtime.Numerics
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Runtime.Numerics.dll
> ----------------------------------------
> System.Reflection.Emit.Lightweight
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Reflection.Emit.Lightweight.dll
> ----------------------------------------
> Anonymously Hosted DynamicMethods Assembly
>     Assembly Version: 0.0.0.0
>     Location: 
> ----------------------------------------
> System.Net.Quic
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Net.Quic.dll
> ----------------------------------------
> System.Net.NetworkInformation
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Net.NetworkInformation.dll
> ----------------------------------------
> System.Console
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Console.dll
> ----------------------------------------
> System.Diagnostics.StackTrace
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Diagnostics.StackTrace.dll
> ----------------------------------------
> System.Reflection.Metadata
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Reflection.Metadata.dll
> ----------------------------------------
> System.Collections.Immutable
>     Assembly Version: 8.0.0.0
>     Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.10\System.Collections.Immutable.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************

**Comment by Jettcodey** [comment]
Fixed in new Release 1.3.3
