### ISSUE TITLE
[Feature Request] Add an option for selecting where to save the files to. 

### ISSUE THREAD

**Issue by QuantumQuokka2** [Jettcodey/TikTok-Downloader#22]
It's very annoying when I want to do mass downloading and I always have to free up space since it automatically saves in the desktop. it will be appreciated if you could add another textbox to write the location where I want it to be saved. thank you so much! :)

**Comment by Jettcodey** [comment]
Please Take a look at the Options in The Application first.

![image](https://github.com/user-attachments/assets/7da8fb19-6e50-4bcb-b8b2-704a565904b8)
