### ISSUE TITLE
Error when gathering videos info from username

### ISSUE THREAD

**Issue by AksharDP** [Jettcodey/TikTok-Downloader#9]
When you try to download videos via username, the browser will pop up and in place of the videos it will say "Something went wrong Sorry about that! Please try again later." with a "Refresh" button underneath the text. There is no text printed in Latest Download Status either.

Edit: So I tried downloading multiple times (like 6 times) and on the 7th time for some reason the videos loaded. I don't know if you can do anything about this, but it just seems annoying to have to retry multiple times.

**Comment by Jettcodey** [comment]
Hi,

Thank you for reporting this issue. I will look into it as soon as possible.

It seems that the problem might be related to newer browser versions, which could be causing some incompatibility issues. This might explain why you are seeing the "Something went wrong. Sorry about that! Please try again later." message and the need to retry multiple times before the videos load.

Maybe if you could tell me which browser and version you are using, it would help me a lot.

I appreciate your patience and will update you once I have more information or a fix. In the meantime, if you encounter any other details or patterns that might help, please let me know.

**Comment by AksharDP** [comment]
> Hi,
> 
> Thank you for reporting this issue. I will look into it as soon as possible.
> 
> It seems that the problem might be related to newer browser versions, which could be causing some incompatibility issues. This might explain why you are seeing the "Something went wrong. Sorry about that! Please try again later." message and the need to retry multiple times before the videos load.
> 
> Maybe if you could tell me which browser and version you are using, it would help me a lot.
> 
> I appreciate your patience and will update you once I have more information or a fix. In the meantime, if you encounter any other details or patterns that might help, please let me know.

I am currently using brave browser "[Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (64-bit)"

**Comment by Jettcodey** [comment]
Hey @AksharDP,

After extensive testing with the Brave browser, I couldn't replicate the issue you described. It’s possible that a browser extension, such as an ad blocker, cookie blocker, or the VPN service of Brave (if you're using it), could be causing the problem.

Sorry for the inconvenience. You might try disabling these extensions, reinstalling Brave, or using a different browser to see if that resolves the issue.

I do plan adding an option to specify a different browser in a future update.

**Comment by AksharDP** [comment]
> Hey @AksharDP,
> 
> After extensive testing with the Brave browser, I couldn't replicate the issue you described. It’s possible that a browser extension, such as an ad blocker, cookie blocker, or the VPN service of Brave (if you're using it), could be causing the problem.
> 
> Sorry for the inconvenience. You might try disabling these extensions, reinstalling Brave, or using a different browser to see if that resolves the issue.
> 
> I do plan adding an option to specify a different browser than the systems default in a future update.

Alright no worries, thank for the help. Idk if you want me to close the issue or not, ill leave it up to you.

**Comment by eightsideddie** [comment]
Hello, 

Apologies if you'd rather I just create a new issue. First time user here having the same problem. I'm attempting a "Mass Download by Username" and it opens a Microsoft Edge InPrivate window where I see this.

![image](https://github.com/user-attachments/assets/418d9fde-55bc-4698-be4a-abc41ed306ec)

I'm using Microsoft Edge _Version 131.0.2903.86 (Official build) (64-bit)_, I disabled all extensions. I don't suppose there is an easy way for the application to try another browser I have installed? Perhaps it's based on what the default browser is?

FWIW, when I manually/normally go to the URL I provide, I can see the page normally.

Thank you very much for your time.

**Comment by eightsideddie** [comment]
Oh man, totally missed the Options! 

I tried Google Chrome and Brave Browser, unfortunately getting the same result, but I wasn't able to try Firefox (which I was more optimistic about) because of this path error:

![image](https://github.com/user-attachments/assets/11b32b79-eb6d-4767-a257-5de93a266c53)

I understand that something probably changed, which is annoying.

In the meanwhile, I'm going to try from different computers. Thank you for your time!
